### PR TITLE
Add integer scaling feature and make client window resizable

### PR DESCRIPTION
**Pull request by SadPencil**
This PR:
1. Adds integer scaling support for rendering the client. This feature is by default turned off.
2. Makes the client window resizable for DX and XNA builds if integer scaling is turned **ON**.
3. Improves 1.5x scaling for 1920x1080/1920x1200 if integer scaling is turned **OFF**.
4. Introduces some default options that can be defined in `[UserDefaults]` section in `ClientDefinitions.ini` file by modders.
5. Downgrades the DPI awareness from PerMonitorV2 to SystemAware for OGL builds to prevent weird GL window resizing when moving the client window between two monitors with different DPI settings. DX and XNA builds stay in PerMonitorV2. UGL build stays in SystemAware.

## Note for 3:
`1280x720` will be selected as the render resolution (if valid) if the window size is `1920x1080` (1.5x). Same for `1280x800 -> 1920x1200` (1.5x).

## Note for 2:
This PR makes the client window resizable for DX and XNA builds **if integer scaling is turned on**. Note: the render resolution is not changed upon a window resizing event. It can only be changed when client restarts itself. This should not be a big issue since the minimum and maximum render resolution are close.

## Note for 4: 

The following default options can be defined in `[UserDefaults]` section in `ClientDefinitions.ini` file by modders:
- BorderlessWindowedClient
- IntegerScaledClient
- WriteInstallationPathToRegistry

Users can override these options in user settings.

## Note for 1:

To turn on integer scaling feature, modders need to specify 
```ini
[UserDefaults]
IntegerScaledClient=true
``` 
in `ClientDefinitions.ini` file.

Users can override this option from user ini settings file (e.g., `Settings.ini`):
```ini
[Video]
IntegerScaledClient=true
```
----

Project Phantom as an example:

`ClientDefinitions.ini`:
```ini
[Settings]
MinimumRenderWidth=1280
MinimumRenderHeight=768
MaximumRenderWidth=1366
MaximumRenderHeight=800
RecommendedResolutions=1280x768,1280x800,1366x800

[UserDefaults]
IntegerScaledClient=true
```

Snipaste_2024-09-11_02-03-51
Snipaste_2024-09-11_02-04-42
Snipaste_2024-09-11_02-05-17
Snipaste_2024-09-11_02-06-18

## Dependencies:

Requires:

https://github.com/Rampastring/Rampastring.XNAUI/pull/34

```diff
diff --git a/Rampastring.XNAUI.csproj b/Rampastring.XNAUI.csproj
index b4a94f6..156de3a 100644
--- a/Rampastring.XNAUI.csproj
+++ b/Rampastring.XNAUI.csproj
@@ -151,4 +151,9 @@
     <PackageReference Include="SixLabors.ImageSharp" Version="2.1.7" />
     <PackageReference Include="TextCopy" Version="6.2.1" />
   </ItemGroup>
+       <PropertyGroup>
+               <VersionPrefix>2.3.21</VersionPrefix>
+               <VersionSuffix>private-intscale-061a412</VersionSuffix>
+       </PropertyGroup>
+
 </Project>
```

### CODE REVIEW

**Comment by SadPencil** [comment]
TODO: remove PreferedRenderWidth and PreferedRenderHeight

Find a way to minimize black surroundings

**Comment by SadPencil** [comment]
Ready for review. Require XNAUI PR 34 be merged first.

**Comment by SadPencil** [comment]
> 11.09. 13:44:44.808    InitGraphicsMode: 1366x768
> 11.09. 13:44:44.817    Setting render resolution to 1366x768. Integer scaling: True
> 
> 11.09. 13:45:01.690    InitGraphicsMode: 1280x960
> 11.09. 13:45:01.699    Setting render resolution to 1280x800. Integer scaling: True
> 
> 11.09. 13:46:09.920    InitGraphicsMode: 1400x1050
> 11.09. 13:46:09.931    Setting render resolution to 1366x800. Integer scaling: True
> 
> 11.09. 13:46:49.921    InitGraphicsMode: 1600x900
> 11.09. 13:46:49.930    Setting render resolution to 1366x800. Integer scaling: True
> 
> 11.09. 13:48:59.331    InitGraphicsMode: 1920x1080
> 11.09. 13:48:59.340    Setting render resolution to 1366x800. Integer scaling: True
> 
> 11.09. 13:49:23.797    InitGraphicsMode: 2560x1440
> 11.09. 13:49:23.807    Setting render resolution to 1366x800. Integer scaling: True
> 
> 11.09. 13:49:42.087    InitGraphicsMode: 2560x1600
> 11.09. 13:49:42.096    Setting render resolution to 1280x800. Integer scaling: True
> 
> 11.09. 13:50:21.140    InitGraphicsMode: 3840x2160
> 11.09. 13:50:21.150    Setting render resolution to 1366x800. Integer scaling: True

**Comment by MahBoiDeveloper** [comment]
Why is it necessary to open and edit `ClientDefinitions.ini` to enable integer scaling? Maybe it would be better to add a checkbox in `Options` → `Display`?

**Comment by Metadorius** [comment]
> Why is it necessary to open and edit `ClientDefinitions.ini` to enable integer scaling? Maybe it would be better to add a checkbox in `Options` → `Display`?

You don't need to, it's to adjust the default setting. The integer scaling is saved to settings INI.

**Comment by MahBoiDeveloper** [comment]
> > Why is it necessary to open and edit `ClientDefinitions.ini` to enable integer scaling? Maybe it would be better to add a checkbox in `Options` → `Display`?
> 
> You don't need to, it's to adjust the default setting. The integer scaling is saved to settings INI.

This feature is disabled by default and users for enabling it would edit INI file instead of having user friendly checkbox in client Options.

> Adds integer scaling support for rendering the client. This feature is by default turned off.

I believe it would be better to add feature configurable from client, but not only from `.ini` files.

**Comment by Metadorius** [comment]
My point was not to refute the need of a checkbox, which I agree is needed (SadPencil told me he isn't sure yet how to correctly add one and is currently busy so maybe you could help him out), but to correct that you don't need to edit `ClientDefinitions.ini` in order for this to work.

**Comment by MahBoiDeveloper** [comment]
> My point was not to refute the need of a checkbox, which I agree is needed (SadPencil told me he isn't sure yet how to correctly add one and is currently busy so maybe you could help him out), but to correct that you don't need to edit `ClientDefinitions.ini` in order for this to work.

I've made a [PR](https://github.com/SadPencil/xna-cncnet-client/pull/5) into @SadPencil's repo to add this checkbox. @Metadorius, check it too please.

image

**Pull request merged**
