### PR TITLE
Disable all private messages

### PR DESCRIPTION
**Pull request by devo1929**
image

image

OLD UI for reference
image

### CODE REVIEW

**Comment by Metadorius** [comment]
Maybe it would be good to also have a function to disable messages from non-friends?

**Comment by devo1929** [comment]
> Maybe it would be good to also have a function to disable messages from non-friends?

Easily doable. I would add it as another "sub" option under the Disable Private Messages. Does it need to be in this PR?

**Comment by Metadorius** [comment]
As you wish, I'd group them together but I don't mind either way.

**Comment by devo1929** [comment]
@Metadorius 
image

image

**Comment by Metadorius** [comment]
hmm not sure if it is intuitive this way, on the other thought... maybe it would be better to do a drop-down called `Allow PMs from:` with options `Everyone`, `Friends` and `No one` and keep `Disable PM Popups` like it was before?

**Comment by devo1929** [comment]
> hmm not sure if it is intuitive this way, on the other thought... maybe it would be better to do a drop-down called `Allow PMs from:` with options `Everyone`, `Friends` and `No one` and keep `Disable PM Popups` like it was before? because I had to read into the names of the checkboxes for a good minute before realizing how do they interact.

Killin me...

**Comment by devo1929** [comment]
> hmm not sure if it is intuitive this way, on the other thought... maybe it would be better to do a drop-down called `Allow PMs from:` with options `Everyone`, `Friends` and `No one` and keep `Disable PM Popups` like it was before? because I had to read into the names of the checkboxes for a good minute before realizing how do they interact.

I'm not against this, but it would require refactor, not only to what I've done recently.

**Comment by Metadorius** [comment]
Then perhaps a different wording on the checkbox would help? Something like "Allow friends to PM", or invert checkbox and call it "Block PMs from friends as well".

**Comment by devo1929** [comment]
> Then perhaps a different wording on the checkbox would help? Something like "Allow friends to PM", or invert checkbox and call it "Block PMs from friends as well".

I do like your drop down idea. The refactoring required would be to create a new INI property that would hold the "state" of this drop down and then being backwards compatible with the existing Disable PM Popups setting. IE, it would need converted. Alternatively, we leave it as 3 separate boolean properties as it currently is in the INI and have the drop down change event responsible for changing all 3 of those values.
Thoughts?

**Comment by Metadorius** [comment]
I don't think backwards compatibility is needed though? Popups will stay the same old checkbox, it's just that the new PM disable settings would be done via a dropdown. That is if we do it soon enough, before the version with checkboxes goes into mods and YR client. But if we aren't gonna do that now I suggest just to apply rewording to remove confusion element.

**Comment by devo1929** [comment]
Ah, you're correct. For some reason, I was thinking the "popup" one would need to be in the drop down.

**Pull request merged**
