### PR TITLE
Multi Language Support To The Client And Increase Security.

### PR DESCRIPTION
**Pull request by AlperenFural**
- For Now, Multiple Language Support Has Only Added In The Headings In The Settings Panel
- Multi-Language Support Currently Includes Only Russian, English And Turkish.
- Game Broadcast Channel Channel Password Feature Added.
- The passwords in the rooms that were established were sent to the Game Broadcast Channel

### CODE REVIEW

**Comment by AlperenFural** [comment]
Screenshot_1
Screenshot_2

**Comment by AlperenFural** [comment]
Şimdilik Sorunsuz Çalışıyor. Ama İstemcide Çevrilecek Çok Fazla Kelime Var.

**Comment by pzhlkj6612** [comment]
Hi, I think these changes should be put into two PRs. One for "security" and the other for "multilingual UI".

**Comment by AlperenFural** [comment]
I just thought of doing these for yr. unfortunately I don't have time to translate for all versions.

**Comment by Metadorius** [comment]
This is not the desired way of doing translations. You're basically hardcoding another set of strings into the game code, which is the worst possible solution. Also please, don't translate into the language you don't know, that Russian is broken.

**Comment by AlperenFural** [comment]
In The Initial Phase Only This Code Build Is Not Finished Yet. And I Added The Russian Language For Trial Purposes Only. Of course I will not translate all of everything.

**Comment by Metadorius** [comment]
You're going the completely wrong way. There is already a branch with a base for translation feature that has to be done via reflection, but to be done properly it needs quite a a bit of effort to make. We are **not** going to do it via hardcode.

**Comment by AlperenFural** [comment]
The Room Codes set up in the lobby are now written on the cncnet-yr-games channel, so the channel key must be put on the cncnet-yr-games channel. Increase the authority of administrators so that only the administrator can see them.

**Comment by AlperenFural** [comment]
The channel key must be added to the cncnet-yr-games channel, so otherwise everyone will be able to see the set room passwords.

**Comment by Metadorius** [comment]
Passwords should never be leaked into a public channel. You don't seem to really understand the concept of security. Also the "multi-language support" isn't really a support, you're just changing hardcoded strings.

**Pull request closed without merging**
