### PR TITLE
Make gitversion conditionally included with .git folder

### PR DESCRIPTION
**Pull request by devo1929**

### CODE REVIEW

**Review by Rans4ckeR — CHANGES_REQUESTED** [review]
This still has problems unfortunately. I would prefer removing the NuGet package and adding the necessary steps in the workflow.

Try this for example in a new folder:

`git clone -b conditional-gitversion --single-branch https://github.com/devo1929/xna-cncnet-client.git`

When building the solution:

> System.InvalidOperationException: Gitversion could not determine which branch to treat as the development branch (default is 'develop') nor release-able branch (default is 'main' or 'master'), either locally or remotely. Ensure the local clone and checkout match the requirements or considering using 'GitVersion Dynamic Repositories'

**Comment by SadPencil** [comment]
I prefer tell developers always get codes via git clone

**Comment by devo1929** [comment]
> I would prefer removing the NuGet package and adding the necessary steps in the workflow.

The NuGet package is what automatically embeds the version in the assembly.

**Comment by devo1929** [comment]
> I prefer tell developers always get codes via git clone

I tend to agree. Maybe instead of making the package conditional on the existence of a .git folder, it throws a warning or even error message when the .git folder doesn't exist when attempting to build.

**Pull request closed without merging**
